esphome:
  name: esp-sitting-room-socket

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-sitting-socket"
    password: "esp-sitting-socket"

captive_portal:

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20


i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

switch:
  - platform: gpio
    name: "Relay 1"
    pin: GPIO25
    id: relay1
  - platform: gpio
    name: "Relay 2"
    pin: GPIO33
    id: relay2
  - platform: gpio
    name: "Relay 3"
    pin: GPIO26
    id: relay3

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: oled
    address: 0x3C
    lambda: |-
      it.print(0, 10, id(roboto), "Hello World!");
