esphome:
  name: esp-sitting-room-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-39A964"
    password: "h0f5MEHUibYe"

captive_portal:


i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

output:
  - platform: gpio
    id: led
    pin: GPIO2


light:
  - platform: binary
    name: "Sitting Room Sensor"
    output: led

sensor:
  - platform: mcp9808
    name: "Sitting Room Temperature"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "Sitting Room Door"

  - platform: gpio
    pin: 
      number: GPIO4
      mode:
          input: true
          pulldown: true
    name: "Lazy Button A"



